### ISSUE TITLE
I need to go someone where to get help about my son who, I believe, is drinking but won't talk to me about it.

### ISSUE THREAD

**Issue by Dawnie71** [Dawnie71/Teen-alcohol#2]
**User Story:**
My son has come home a few times from his friends house, smelling of alcohol. He refuses to talk to me but I have heard he has been let go from the football team. 

**Acceptance Criteria:** 
- [x] The parent user can access information about the signs of teen alcohol use and misuse.
- [x] The user can find tips on how to talk to their teen about alcohol.
- [x] The user can access resources for parenting support and family counseling.

**Tasks:** 
- [x] Create informative content, such as articles and webinars.
- [x] Design a user-friendly interface that is easy to navigate.
- [x] Offer a parent support forum or community.
