### ISSUE TITLE
I want to raise awareness of this issue in our village.

### ISSUE THREAD

**Issue by Dawnie71** [Dawnie71/Teen-alcohol#6]
****User Story:**
i live in the village and have trouble with teenagers drinking in the local play parks. I have tried to these youngsters and feel they need information to understand the harm they are causing to themselves and the village. 

**Acceptance Criteria:**** 
- [ ] The user can easily find information and resources on how to tackle behaviours.
- [ ] A noticeboard for events in the local community.

**Tasks:** 
- [ ] List local organisations to advise people who to call or what action to take when they witness this behaviour.
- [ ] Provide information about who and where to signpost people who need help.
